{% set version = "0.2.2" %}

package:
  name: xesmf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xesmf/xesmf-{{ version }}.tar.gz
  sha256: e38f712b12eb2f616d6373669ce9dd73f2138dccc5846c9b7cee73a835c87be7

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - esmpy
    - xarray
    - numpy
    - scipy

test:
  imports:
    - xesmf

about:
  home: https://github.com/JiaweiZhuang/xESMF
  license: MIT
  license_file: LICENSE
  summary: 'Universal Regridder for Geospatial Data'
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
    - JiaweiZhuang
