{% set version = "0.1.2" %}

package:
  name: xesmf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xesmf/xesmf-{{ version }}.tar.gz
  sha256: 0e00a293ec8a19938c81a2e62b3b389c2df2d636ee08a5a745c27295a8e18565

build:
  number: 0
  skip: True  # [py2k or win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - esmpy
    - xarray
    - numpy
    - scipy

test:
  imports:
    - xesmf

about:
  home: https://github.com/JiaweiZhuang/xESMF
  license: MIT
  summary: 'Universal Regridder for Geospatial Data'
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
