{% set name = "xesmf" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5a2c4b3e8dbbc9fccd5772a940f9067d68e824215ef87ba222b06718c4eeb56

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<3.12
    - pip
    - setuptools >=41.2
    - setuptools_scm
    - wheel
  run:
    - python >=3.8,<3.12
    - cf_xarray >=0.5.1
    - esmpy >=8.0.0
    - numba >=0.55.2
    - numpy >=1.16
    - shapely
    - sparse >=0.8.0
    - xarray >=0.16.2

test:
  requires:
    - pip
    - pytest
    - dask
    - cftime
  imports:
    - xesmf
  commands:
    # needs to fix: esmpy 8.4.0 requires pytest-json-report, which is not installed.
    # - pip check
    - python -m pytest --pyargs xesmf

about:
  home: https://github.com/pangeo-data/xESMF
  license: MIT
  license_file: LICENSE
  summary: Universal Regridder for Geospatial Data
  license_family: MIT

extra:
  recipe-maintainers:
    - aulemahal
    - ocefpaf
    - JiaweiZhuang
    - raphaeldussin
    - huard
    - zklaus
