{% set version = "0.4.0" %}

package:
  name: xesmf
  version: {{ version }}

source:
  url: https://github.com/pangeo-data/xESMF/archive/v{{ version }}.tar.gz
  sha256: 11cbefbd508c419f37ed3ba45cf0ff873c4798957891b5bb069354b2872bbff1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - python >=3.6
    - esmpy >=8.0.0
    - numpy
    - scipy
    - xarray

test:
  imports:
    - xesmf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pangeo-data/xESMF
  license: MIT
  license_file: LICENSE
  summary: Universal Regridder for Geospatial Data
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
    - JiaweiZhuang
