{% set version = "0.3.0" %}

package:
  name: xesmf
  version: {{ version }}

source:
  url: https://github.com/JiaweiZhuang/xESMF/archive/v{{ version }}.tar.gz
  sha256: 589d425b65b21b4f054873e53dcf3755299d4d649b653c3c1c04a4777f14af64

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - esmpy
    - numpy
    - scipy
    - xarray

test:
  imports:
    - xesmf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JiaweiZhuang/xESMF
  license: MIT
  license_file: LICENSE
  summary: Universal Regridder for Geospatial Data
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
    - JiaweiZhuang
