{% set name = "xesmf" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 426247ee09a963579102082a6820ccebe7c016eaa6a1c0cd7453657341d210c0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - python >=3.6
    - esmpy >=8.0.0
    - xarray >=0.16.2
    - numpy >=1.16
    - shapely <2.0
    - cf_xarray >=0.5.1
    - sparse >=0.8.0
    - numba >=0.55.2

test:
  requires:
    - pip
    - pytest
    - dask
    - cftime
  imports:
    - xesmf
  commands:
    # needs to fix: esmpy 8.4.0 requires pytest-json-report, which is not installed.
    # - pip check
    - python -m pytest --pyargs xesmf

about:
  home: https://github.com/pangeo-data/xESMF
  license: MIT
  license_file: LICENSE
  summary: Universal Regridder for Geospatial Data
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
    - JiaweiZhuang
    - raphaeldussin
    - huard
    - zklaus
