travis:
  secure:
    BINSTAR_TOKEN: vw5n3ZwnKX03gHj9NS3erSMOkmedZxy8LQ2vTKKykbpR6YvHVqAyCePbpaHBsCgBHn7ZXRO1yPOs82CoWHIpoKHj3JeqRPzVHhRvuib6AnrApUj5E0LgfiJSQtewbP66h/qZchF1fRP9wtzi77Qg0K+I5caIS+xv+AzdXRqpQ8FebKoXqxidSGGfWQw6GfDnj63a8qptglZu61lQw0qKy+629EBEqM6n6QM9rV4j37h7eW1YilsQsFOIIP7f3Bo+fJGktYSvF33x4UB1rpeeFNZkNckLhBTQRa5FA+QtSYam200uRPmnwEMr3rQtUFxQhtz53N2zpgPql4SL+82V+4AigLjRMdC1uLKI+1vYdJ6vDRPziyxelKLCV69SuQialCETdh2zUBiBumXt2HnD/fBS29uzefc8SjoA6/+oDFkcBAZ1pJf4PtzdKEZSUCr6ij/0ARX58SPsOrNnTNQei4Y5amnlbZUeW+fMJXvvSYMnePs0DhNQuikadmdz1FtDgkBTT0fRYdpSzmJfElmLegrvzZWdH2Ig9O1Jhk9lK0r+CkHygOOe3hFHmKkNnenPIGNBCzxbarKwpxk0H6BbvS0LyNMo1KY30k09st79hJ3TLINRLPFTNjnfitPHByB3b+eG5NIDERjSzEFr38dkdkI0DHTmhpsEhSImkY22pz4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
