travis:
  secure:
    BINSTAR_TOKEN: gnsWcDHTCI5MJNDT2ofsAi6Z5bASiD3WwVmBDdJnl0/s/RJSfLlIF5V8q2fEbB1xkg1b5HuoKMa0AJyHmotRRnaHU4pJY1Svg7igOEvvLKCH/qhhpCZ0bgZW9f7mW5gssNPt61XSZFLfVMZJ7T7gW/3BbFi/mu1+cVKu0vWEEC4+L0A2lJ9SxZxkNE8RYxvokI7oFNTeYkCm7yKJ5OEPcWyPGAbQ+u7itb7MtTF+Qww1HpCHPHnpa7NCUwnBeMMOZcBIp4sY6vF39m5bxcwPM/UEXlGv/rQ+zO8EjFvre0hs83XC0YEFCO0G+Xk389CBSHK4eIMavPJWkM7Bz9gJZfJORU8wVcHMMwoaW+4p3YzDYLMlkBTHzmt9oydXHt+QTo3Noy1n4grFuKTBhYC6aOBKjinfyfIHWmJ353IsZy9Ij6+v+9Twi/Ol2D8ZpmfqayT1joprvTn/8Eep3ecminLwo5BNwdd1450/hzEe7Hr028PXb/8j+AGnLccs1tCZV0B7qkQp8+ahL+ZQc9AZypF1af1vBo8Zc7/t7/ECzoZf87qB9Aj+T1AIxnnEh2IcDwLKFwF/yUE9FOZAvvzmf8lpOvdugrrpo1z1mF5W9s1zylPaRqImlYfMcGhigPbhJCnUyPNaXEsseXwCLDXz3C7IptG8e0ni17YS6Z1tfqQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
